CREATE CONSTRAINT ON (x:Product) ASSERT x.id  IS UNIQUE;
CREATE CONSTRAINT ON (x:Bank) ASSERT x.id  IS UNIQUE;
CREATE CONSTRAINT ON (x:Account) ASSERT x.id  IS UNIQUE;
CREATE CONSTRAINT ON (x:Profile) ASSERT x.id  IS UNIQUE;
CREATE CONSTRAINT ON (x:Company) ASSERT x.id  IS UNIQUE;
CREATE CONSTRAINT ON (x:Purchase) ASSERT x.id  IS UNIQUE;
